language: node_js
node_js:
- node
- '7'
- '6'
deploy:
  provider: npm
  email: nicolasmatthieu57@gmail.com
  api_key:
    secure: jbPUO4ggV+A8USN3aqhZ59bjav1UUiCHvLT+B/aj+XnjMv8fAH6XgdF/eb4k/nQOdg9S3VfwHnVv5FKG+6SWufDuwAoGVNiZPcsKFtlPta97YfxgICRmk5DcK4jpqfG0/jmDc1K/W710zKIjxgYHCb1ZukWF4v20DOIz7NL0diM=
  on:
    tags: true
    repo: coast-team/mute-structs
  skip_cleanup: true
